//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.CHUCVUs = new HashSet<CHUCVU>();
        }
    
        public string UserName { get; set; }
        public string Pass { get; set; }
        public int quyen { get; set; }
    
        public virtual ICollection<CHUCVU> CHUCVUs { get; set; }
    }
}
