//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCVU
    {
        public CHUCVU()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string TenChucVu { get; set; }
        public Nullable<int> quyen { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
