//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NhaHangEntities1 : DbContext
    {
        public QL_NhaHangEntities1()
            : base("name=QL_NhaHangEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public DbSet<BANAN> BANANs { get; set; }
        public DbSet<CHITIET_HD> CHITIET_HD { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<MONAN> MONANs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<NHOMMONAN> NHOMMONANs { get; set; }
        public DbSet<PHIEUTHANHTOAN> PHIEUTHANHTOANs { get; set; }
    }
}
