//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        public MONAN()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MaNhom { get; set; }
    
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual NHOMMONAN NHOMMONAN { get; set; }
    }
}
