//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUTHANHTOANs = new HashSet<PHIEUTHANHTOAN>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string UserName { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string ChucVu { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<double> LuongCB { get; set; }
    
        public virtual CHUCVU CHUCVU1 { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<PHIEUTHANHTOAN> PHIEUTHANHTOANs { get; set; }
    }
}
